users_on_page: 10
tours_on_page: 10
default_email: 'thatv1212@gmail.com'
high_avatar_icon: 24
width_avatar_icon: 24
peoples_booking_tours: 1
peoples_booking_min: 1
time_during_min: 1
price_min: 0
success_3_days: 3
host: "localhost:3000"
over_time: "This booking is overtime, auto cancel "
